version: "3.8"

services:
  web:
    build: ./web
    container_name: nextjs
    volumes:
      - ./web:/app
    ports:
      - "3017:3000"
    environment:
      - NODE_ENV="" # disable production mode
    entrypoint: sh -c "yarn dev"

  api:
    image: golang:alpine3.16
    container_name: api
    restart: "always"
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "5017:5000"
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=mysql:3306
      - MYSQL_NET=tcp
    entrypoint: sh -c "FUNCTION_TARGET=hello go run ./entrypoint/main.go"

  api-migrate:
    image: golang:alpine3.16
    container_name: api-migrate
    restart: "always"
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "5018:5000"
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=mysql:3306
      - MYSQL_NET=tcp
    entrypoint: sh -c "FUNCTION_TARGET=migrate go run ./entrypoint/main.go"
  mysql:
    image: mysql
    container_name: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8017:8080"
    volumes:
      - ./swagger:/tmp/swagger
    environment:
      SWAGGER_JSON: /tmp/swagger/openapi.yml
