version: '3.8'

services:
  web:
    build: ./web
    container_name: nextjs
    volumes:
      - ./web:/app
    ports:
      - "3017:3000"
    environment:
      - NODE_ENV="" # disable production mode
    entrypoint: sh -c "yarn dev"

  api:
    image: golang:alpine3.16
    container_name: api
    restart: "always"
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "5017:5000"
    entrypoint: sh -c "go run migrate/migrate.go && FUNCTION_TARGET=hello go run ./entrypoint/main.go"

  mysql:
    image: mysql
    container_name: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=testDatabase
      - MYSQL_USER=testUser
      - MYSQL_PASSWORD=testPassword
