// Code generated by ent, DO NOT EDIT.

package mesuringpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/hmdyt/satori_codingtest-2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// BodyMass applies equality check predicate on the "body_mass" field. It's identical to BodyMassEQ.
func BodyMass(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBodyMass), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.MesuringPoint {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.MesuringPoint {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserID), v))
	})
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserID), v))
	})
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserID), v))
	})
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserID), v))
	})
}

// BodyMassEQ applies the EQ predicate on the "body_mass" field.
func BodyMassEQ(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBodyMass), v))
	})
}

// BodyMassNEQ applies the NEQ predicate on the "body_mass" field.
func BodyMassNEQ(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBodyMass), v))
	})
}

// BodyMassIn applies the In predicate on the "body_mass" field.
func BodyMassIn(vs ...float64) predicate.MesuringPoint {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldBodyMass), v...))
	})
}

// BodyMassNotIn applies the NotIn predicate on the "body_mass" field.
func BodyMassNotIn(vs ...float64) predicate.MesuringPoint {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldBodyMass), v...))
	})
}

// BodyMassGT applies the GT predicate on the "body_mass" field.
func BodyMassGT(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBodyMass), v))
	})
}

// BodyMassGTE applies the GTE predicate on the "body_mass" field.
func BodyMassGTE(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBodyMass), v))
	})
}

// BodyMassLT applies the LT predicate on the "body_mass" field.
func BodyMassLT(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBodyMass), v))
	})
}

// BodyMassLTE applies the LTE predicate on the "body_mass" field.
func BodyMassLTE(v float64) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBodyMass), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MesuringPoint {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MesuringPoint {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MesuringPoint) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MesuringPoint) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MesuringPoint) predicate.MesuringPoint {
	return predicate.MesuringPoint(func(s *sql.Selector) {
		p(s.Not())
	})
}
