// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hmdyt/satori_codingtest-2/ent/mesuringpoint"
	"github.com/hmdyt/satori_codingtest-2/ent/predicate"
)

// MesuringPointDelete is the builder for deleting a MesuringPoint entity.
type MesuringPointDelete struct {
	config
	hooks    []Hook
	mutation *MesuringPointMutation
}

// Where appends a list predicates to the MesuringPointDelete builder.
func (mpd *MesuringPointDelete) Where(ps ...predicate.MesuringPoint) *MesuringPointDelete {
	mpd.mutation.Where(ps...)
	return mpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mpd *MesuringPointDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mpd.hooks) == 0 {
		affected, err = mpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MesuringPointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mpd.mutation = mutation
			affected, err = mpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mpd.hooks) - 1; i >= 0; i-- {
			if mpd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mpd *MesuringPointDelete) ExecX(ctx context.Context) int {
	n, err := mpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mpd *MesuringPointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mesuringpoint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mesuringpoint.FieldID,
			},
		},
	}
	if ps := mpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// MesuringPointDeleteOne is the builder for deleting a single MesuringPoint entity.
type MesuringPointDeleteOne struct {
	mpd *MesuringPointDelete
}

// Exec executes the deletion query.
func (mpdo *MesuringPointDeleteOne) Exec(ctx context.Context) error {
	n, err := mpdo.mpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mesuringpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mpdo *MesuringPointDeleteOne) ExecX(ctx context.Context) {
	mpdo.mpd.ExecX(ctx)
}
