// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hmdyt/satori_codingtest-2/ent/mesuringpoint"
	"github.com/hmdyt/satori_codingtest-2/ent/predicate"
)

// MesuringPointQuery is the builder for querying MesuringPoint entities.
type MesuringPointQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MesuringPoint
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MesuringPointQuery builder.
func (mpq *MesuringPointQuery) Where(ps ...predicate.MesuringPoint) *MesuringPointQuery {
	mpq.predicates = append(mpq.predicates, ps...)
	return mpq
}

// Limit adds a limit step to the query.
func (mpq *MesuringPointQuery) Limit(limit int) *MesuringPointQuery {
	mpq.limit = &limit
	return mpq
}

// Offset adds an offset step to the query.
func (mpq *MesuringPointQuery) Offset(offset int) *MesuringPointQuery {
	mpq.offset = &offset
	return mpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mpq *MesuringPointQuery) Unique(unique bool) *MesuringPointQuery {
	mpq.unique = &unique
	return mpq
}

// Order adds an order step to the query.
func (mpq *MesuringPointQuery) Order(o ...OrderFunc) *MesuringPointQuery {
	mpq.order = append(mpq.order, o...)
	return mpq
}

// First returns the first MesuringPoint entity from the query.
// Returns a *NotFoundError when no MesuringPoint was found.
func (mpq *MesuringPointQuery) First(ctx context.Context) (*MesuringPoint, error) {
	nodes, err := mpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mesuringpoint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mpq *MesuringPointQuery) FirstX(ctx context.Context) *MesuringPoint {
	node, err := mpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MesuringPoint ID from the query.
// Returns a *NotFoundError when no MesuringPoint ID was found.
func (mpq *MesuringPointQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mesuringpoint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mpq *MesuringPointQuery) FirstIDX(ctx context.Context) int {
	id, err := mpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MesuringPoint entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MesuringPoint entity is found.
// Returns a *NotFoundError when no MesuringPoint entities are found.
func (mpq *MesuringPointQuery) Only(ctx context.Context) (*MesuringPoint, error) {
	nodes, err := mpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mesuringpoint.Label}
	default:
		return nil, &NotSingularError{mesuringpoint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mpq *MesuringPointQuery) OnlyX(ctx context.Context) *MesuringPoint {
	node, err := mpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MesuringPoint ID in the query.
// Returns a *NotSingularError when more than one MesuringPoint ID is found.
// Returns a *NotFoundError when no entities are found.
func (mpq *MesuringPointQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mesuringpoint.Label}
	default:
		err = &NotSingularError{mesuringpoint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mpq *MesuringPointQuery) OnlyIDX(ctx context.Context) int {
	id, err := mpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MesuringPoints.
func (mpq *MesuringPointQuery) All(ctx context.Context) ([]*MesuringPoint, error) {
	if err := mpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mpq *MesuringPointQuery) AllX(ctx context.Context) []*MesuringPoint {
	nodes, err := mpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MesuringPoint IDs.
func (mpq *MesuringPointQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mpq.Select(mesuringpoint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mpq *MesuringPointQuery) IDsX(ctx context.Context) []int {
	ids, err := mpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mpq *MesuringPointQuery) Count(ctx context.Context) (int, error) {
	if err := mpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mpq *MesuringPointQuery) CountX(ctx context.Context) int {
	count, err := mpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mpq *MesuringPointQuery) Exist(ctx context.Context) (bool, error) {
	if err := mpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mpq *MesuringPointQuery) ExistX(ctx context.Context) bool {
	exist, err := mpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MesuringPointQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mpq *MesuringPointQuery) Clone() *MesuringPointQuery {
	if mpq == nil {
		return nil
	}
	return &MesuringPointQuery{
		config:     mpq.config,
		limit:      mpq.limit,
		offset:     mpq.offset,
		order:      append([]OrderFunc{}, mpq.order...),
		predicates: append([]predicate.MesuringPoint{}, mpq.predicates...),
		// clone intermediate query.
		sql:    mpq.sql.Clone(),
		path:   mpq.path,
		unique: mpq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MesuringPoint.Query().
//		GroupBy(mesuringpoint.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mpq *MesuringPointQuery) GroupBy(field string, fields ...string) *MesuringPointGroupBy {
	grbuild := &MesuringPointGroupBy{config: mpq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mpq.sqlQuery(ctx), nil
	}
	grbuild.label = mesuringpoint.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.MesuringPoint.Query().
//		Select(mesuringpoint.FieldUserID).
//		Scan(ctx, &v)
func (mpq *MesuringPointQuery) Select(fields ...string) *MesuringPointSelect {
	mpq.fields = append(mpq.fields, fields...)
	selbuild := &MesuringPointSelect{MesuringPointQuery: mpq}
	selbuild.label = mesuringpoint.Label
	selbuild.flds, selbuild.scan = &mpq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a MesuringPointSelect configured with the given aggregations.
func (mpq *MesuringPointQuery) Aggregate(fns ...AggregateFunc) *MesuringPointSelect {
	return mpq.Select().Aggregate(fns...)
}

func (mpq *MesuringPointQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mpq.fields {
		if !mesuringpoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mpq.path != nil {
		prev, err := mpq.path(ctx)
		if err != nil {
			return err
		}
		mpq.sql = prev
	}
	return nil
}

func (mpq *MesuringPointQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MesuringPoint, error) {
	var (
		nodes = []*MesuringPoint{}
		_spec = mpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MesuringPoint).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MesuringPoint{config: mpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mpq *MesuringPointQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mpq.querySpec()
	_spec.Node.Columns = mpq.fields
	if len(mpq.fields) > 0 {
		_spec.Unique = mpq.unique != nil && *mpq.unique
	}
	return sqlgraph.CountNodes(ctx, mpq.driver, _spec)
}

func (mpq *MesuringPointQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := mpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (mpq *MesuringPointQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mesuringpoint.Table,
			Columns: mesuringpoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mesuringpoint.FieldID,
			},
		},
		From:   mpq.sql,
		Unique: true,
	}
	if unique := mpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mesuringpoint.FieldID)
		for i := range fields {
			if fields[i] != mesuringpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mpq *MesuringPointQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mpq.driver.Dialect())
	t1 := builder.Table(mesuringpoint.Table)
	columns := mpq.fields
	if len(columns) == 0 {
		columns = mesuringpoint.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mpq.sql != nil {
		selector = mpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mpq.unique != nil && *mpq.unique {
		selector.Distinct()
	}
	for _, p := range mpq.predicates {
		p(selector)
	}
	for _, p := range mpq.order {
		p(selector)
	}
	if offset := mpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MesuringPointGroupBy is the group-by builder for MesuringPoint entities.
type MesuringPointGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mpgb *MesuringPointGroupBy) Aggregate(fns ...AggregateFunc) *MesuringPointGroupBy {
	mpgb.fns = append(mpgb.fns, fns...)
	return mpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mpgb *MesuringPointGroupBy) Scan(ctx context.Context, v any) error {
	query, err := mpgb.path(ctx)
	if err != nil {
		return err
	}
	mpgb.sql = query
	return mpgb.sqlScan(ctx, v)
}

func (mpgb *MesuringPointGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range mpgb.fields {
		if !mesuringpoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mpgb *MesuringPointGroupBy) sqlQuery() *sql.Selector {
	selector := mpgb.sql.Select()
	aggregation := make([]string, 0, len(mpgb.fns))
	for _, fn := range mpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mpgb.fields)+len(mpgb.fns))
		for _, f := range mpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mpgb.fields...)...)
}

// MesuringPointSelect is the builder for selecting fields of MesuringPoint entities.
type MesuringPointSelect struct {
	*MesuringPointQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mps *MesuringPointSelect) Aggregate(fns ...AggregateFunc) *MesuringPointSelect {
	mps.fns = append(mps.fns, fns...)
	return mps
}

// Scan applies the selector query and scans the result into the given value.
func (mps *MesuringPointSelect) Scan(ctx context.Context, v any) error {
	if err := mps.prepareQuery(ctx); err != nil {
		return err
	}
	mps.sql = mps.MesuringPointQuery.sqlQuery(ctx)
	return mps.sqlScan(ctx, v)
}

func (mps *MesuringPointSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(mps.fns))
	for _, fn := range mps.fns {
		aggregation = append(aggregation, fn(mps.sql))
	}
	switch n := len(*mps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		mps.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		mps.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := mps.sql.Query()
	if err := mps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
