// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hmdyt/satori_codingtest-2/ent/mesuringpoint"
	"github.com/hmdyt/satori_codingtest-2/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mesuringpointFields := schema.MesuringPoint{}.Fields()
	_ = mesuringpointFields
	// mesuringpointDescUserID is the schema descriptor for user_id field.
	mesuringpointDescUserID := mesuringpointFields[0].Descriptor()
	// mesuringpoint.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	mesuringpoint.UserIDValidator = mesuringpointDescUserID.Validators[0].(func(int) error)
	// mesuringpointDescBodyMass is the schema descriptor for body_mass field.
	mesuringpointDescBodyMass := mesuringpointFields[1].Descriptor()
	// mesuringpoint.BodyMassValidator is a validator for the "body_mass" field. It is called by the builders before save.
	mesuringpoint.BodyMassValidator = mesuringpointDescBodyMass.Validators[0].(func(float64) error)
	// mesuringpointDescCreatedAt is the schema descriptor for created_at field.
	mesuringpointDescCreatedAt := mesuringpointFields[2].Descriptor()
	// mesuringpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	mesuringpoint.DefaultCreatedAt = mesuringpointDescCreatedAt.Default.(func() time.Time)
}
