// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MesuringPoint is the predicate function for mesuringpoint builders.
type MesuringPoint func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
